name: first_may

description: first_may application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  data_table_2: ^2.4.2
  #hide app controlls
  bitsdojo_window: ^0.1.5
  window_manager: ^0.3.2
  dropdown_search: ^5.0.6
  excel: ^2.1.0

  #https://pub.dev/packages/dio
  dio: ^5.1.0
  #https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.0.17
  #https://pub.dev/packages/intl
  intl: ^0.17.0
  #https://pub.dev/packages/cached_network_image
  cached_network_image: ^3.2.3
  #https://pub.dev/packages/get
  get: ^4.6.5
  #https://pub.dev/packages/get_storage
  get_storage: ^2.0.3
  #https://pub.dev/packages/material_dialogs
  material_dialogs: ^1.1.4
  #https://pub.dev/packages/flutter_slidable
  flutter_slidable: ^2.0.0
  #https://pub.dev/packages/socket_io_client
  socket_io_client: 1.0.2
  #https://pub.dev/packages/snapping_sheet
  snapping_sheet: ^3.1.0
  #https://pub.dev/packages/flutter_timezone
  flutter_timezone: ^1.0.4
  #https://pub.dev/packages/url_launcher
  url_launcher: ^6.1.8
  #https://pub.dev/packages/jiffy
  jiffy: ^5.0.0
  #https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^8.1.1
  #https://pub.dev/packages/rxdart
  rxdart: ^0.27.1
  #https://pub.dev/packages/auto_route
  auto_route: ^6.0.3
  #https://pub.dev/packages/flutter_secure_storage
  flutter_secure_storage: ^8.0.0
  #https://pub.dev/packages/dartz
  dartz: ^0.10.1
  #https://pub.dev/packages/internet_connection_checker
  internet_connection_checker: ^1.0.0+1
  #https://pub.dev/packages/retrofit
  retrofit: ^4.0.1
  #https://pub.dev/packages/json_annotation
  json_annotation: ^4.8.0
  #https://pub.dev/packages/flutter_svg
  flutter_svg: ^1.1.1+1
  #https://pub.dev/packages/get_it
  get_it: ^7.2.0
  #https://pub.dev/packages/flutter_native_splash
  flutter_native_splash: ^2.2.4
  #https://pub.dev/packages/freezed
  freezed: ^2.1.0
  #https://pub.dev/packages/formz
  formz: ^0.6.0
  #https://pub.dev/packages/pull_to_refresh
  pull_to_refresh: ^2.0.0
  #https://pub.dev/packages/flutter_scale_tap
  flutter_scale_tap: ^1.0.5
  #https://pub.dev/packages/auto_size_text
  auto_size_text: ^3.0.0
  #https://pub.dev/packages/device_info_plus
  device_info_plus: ^8.0.0
  #https://pub.dev/packages/package_info_plus
  package_info_plus: ^3.0.2
  #https://pub.dev/packages/overlay_support
  overlay_support: ^2.0.1
  #https://pub.dev/packages/mask_text_input_formatter/install
  mask_text_input_formatter: ^2.1.0
  #https://pub.dev/packages/modal_bottom_sheet
  modal_bottom_sheet:
    git:
      url: https://github.com/jamesblasco/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet
  #https://pub.dev/packages/flutter_localization
  flutter_localization: ^0.1.10
  #https://pub.dev/packages/flex_color_scheme
  flex_color_scheme: ^7.0.1
  #https://pub.dev/packages/fluttertoast
  fluttertoast: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  analyzer: ^5.0.0
  flutter_launcher_icons: ^0.13.0
  change_app_package_name: ^1.0.0
  flutter_gen_runner: ^5.1.0+1
  dart_code_metrics: ^5.4.0
  flutter_lints: ^2.0.1
  auto_route_generator: ^6.0.0
  retrofit_generator: ^6.0.0+1


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path_ios: "assets/icon.png"
  image_path_android: "assets/icon_foreground.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "assets/icon_background.png"
  adaptive_icon_foreground: "assets/icon_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/images/
    - assets/